3rd-party:
  - src/extras/*

evaluator:
  - src/translator/eval.nim

helpers:
  - src/helpers/*
  
installer:
  - arturo.nimble
  - build.sh

library:
  - src/vm/library/*

package-manager:
  - src/system/module.art

parser:
  - src/translator/parse.nim

repl:
  - src/system/console.art

unit-test:
  - tests/*

vm:
  - src/vm/bytecode.nim
  - src/vm/env.nim
  - src/vm/exec.nim
  - src/vm/globals.nim
  - src/vm/stack.nim
  - src/vm/value.nim

workflows:
  - .github/workflows/*