3rd-party:
  - src/extras/*

evaluator:
  - src/translator/eval.nim

helpers:
  - src/helpers/*
  
installer:
  - arturo.nimble
  - install
  - src/system/update.art

library:
  - src/library/*

package-manager:
  - src/system/module.art

parser:
  - src/translator/parse.nim

repl:
  - src/system/console.art

unit-test:
  - tests/*

vm:
  - src/vm/*

workflows:
  - .github/workflows/*