3rd-party:
  - src/extras/*

documentation:
  - examples/*
  - docs/*

evaluator:
  - src/vm/eval.nim

execution:
  - src/vm/exec.nim

helpers:
  - src/helpers/*
  
installer:
  - arturo.nimble
  - install
  - src/system/update.art

library:
  - src/library/*

package-manager:
  - src/system/module.art

parser:
  - src/vm/parse.nim

repl:
  - src/system/console.art

unit-test:
  - tests/*

error handling: 
  - src/vm/errors.nim

values:
  - src/vm/value.nim

vm:
  - src/vm/*

workflows:
  - .github/workflows/*