3rd-party:
  - src/extras/*

documentation:
  - examples/projecteuler/*
  - examples/rosetta/*
  - docs/*
  - docs/wiki/*

evaluator:
  - src/vm/eval.nim

execution:
  - src/vm/exec.nim

helpers:
  - src/helpers/*
  
installer:
  - install
  - src/scripts/update.art

library:
  - src/library/*

package-manager:
  - package
  - src/vm/packager.nim
  - src/scripts/module.art

parser:
  - src/vm/parse.nim

repl:
  - src/scripts/console.art

unit-test:
  - tests/benchmarks/*
  - tests/unittests/*

error handling: 
  - src/vm/errors.nim

values:
  - src/vm/value.nim

vm:
  - src/vm/*

workflows:
  - .github/workflows/*