language: nim
sudo: required
services:
  - docker
before_install:
  - docker pull fingidor/arturo-nim-docker:0.1
script:
  - docker run -v "$(pwd):/project" -w /project fingidor/arturo-nim-docker:0.1 nim --version
  - docker run -v "$(pwd):/project" -w /project fingidor/arturo-nim-docker:0.1 nimble build -Y "-d:MINI"
