name: "Documentation Updater"

on: 
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths:
      - 'docs/**'

env:
  app-name: arturo

defaults:
  run:
    shell: bash -l {0}

jobs:
  documentation:
    name: "Update Wiki"
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs/wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}