name: "DocGen"

on: workflow_dispatch

env:
  app-name: arturo

defaults:
  run:
    shell: bash -l {0}

jobs:
          
  documentation:
    name: "Generate documentation"
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install Nim
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwebkit2gtk-4.0-dev

      - name: Verify dependecies
        run: |
          nim --version

      - name: Build Arturo
        run: |
          ./install ${{ matrix.version }} log
          echo "$HOME/.arturo/bin" >> $GITHUB_PATH

      - name: Build documentation
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tools/docgen.art

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs/wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}