name: "FreeBSD"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

defaults:
  run:
    shell: bash -l {0}

jobs:  
  freebsd:
    runs-on: macos-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment & Build Arturo
      id: test
      uses: vmactions/freebsd-vm@v0.1.2
      with:
        usesh: true
        prepare: pkg install -y nim bash
        run: |
          ./install mini
          bin/arturo tools/tester.art

# steps:
#   - name: "Cancel similar actions in progress"
#     uses: styfle/cancel-workflow-action@0.6.0
#     with:
#       access_token: ${{ github.token }}

#   - name: "Checkout"
#     uses: actions/checkout@main
#     with:
#       submodules: recursive

#   - name: Install Nim
#     run: |
#       wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
#       echo "$HOME/.nimble/bin" >> $GITHUB_PATH

#   - name: Install dependencies
#     if: matrix.version == 'full'
#     run: |
#       sudo apt-get update
#       sudo apt-get install libwebkit2gtk-4.0-dev
      
#   - name: Verify dependecies
#     run: |
#       nim --version
      
#   - name: Build Arturo
#     run: |
#       ./install ${{ matrix.version }} log
#       echo "$HOME/.arturo/bin" >> $GITHUB_PATH

#   - name: Upload Artifacts
#     uses: 'actions/upload-artifact@v2'
#     with:
#       name: "arturo-${{matrix.version}}-${{matrix.os}}"
#       path: bin/arturo

#   - name: Run unit tests
#     run: |
#       echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
#       arturo tools/tester.art
