name: "FreeBSD"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

defaults:
  run:
    shell: bash -l {0}

jobs:  
  freebsd:
    runs-on: macos-10.15
    strategy:
      matrix:
        os:
          - freebsd-latest
        version:
          - mini
    name: Build & Test
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      # TODO(FreeBSD) Nim compiler package stuck at version 1.6.2
      # labels: enhancement, ci, workflows
      - name: Setup environment & Build Arturo
        id: test
        uses: vmactions/freebsd-vm@v0.1.5
        with:
          usesh: true
          prepare: pkg install -y nim gmp bash databases/sqlite3 libxcb
          run: |
            ./build.nims install ${{ matrix.version }} log
            export PATH="$HOME/.arturo/bin:$PATH"
            arturo tools/tester.art
       
      - name: Upload Artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: "arturo-${{matrix.version}}-${{matrix.os}}"
          path: bin/arturo
