name: "Linux"
on:
  push:
    branches-ignore:
      - 'drkameleon-devel'
    paths-ignore:
      - '*.gif'
      - '*.png'
      - '*.yml'
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '*.gif'
      - '*.png'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

defaults:
  run:
    shell: bash -l {0}

jobs:  
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install Nim
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH
          
      - name: Verify dependecies
        run: |
          nim --version
          
      - name: Build Arturo
        run: |
          ./install mini log
          echo "$HOME/.arturo/bin" >> $GITHUB_PATH

      - name: Upload Artifacts
        uses: 'actions/upload-artifact@v2'
        with:
          name: "arturo-${{matrix.os}}"
          path: bin/arturo

      - name: Run unit tests
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tests/runAll.art