name: Linux
on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  cancel:
    name: "Cleanup"
    runs-on: ubuntu-latest
    steps:
      - name: "Get workflow id"
        run: |
          WORKFLOW_ID=$(curl "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/linux.yml | jq '.id')
          echo "Workflow id: ${WORKFLOW_ID}"
          echo "::set-env name=WORKFLOW_ID::${WORKFLOW_ID}"

      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          access_token: ${{ github.token }}
          workflow_id: ${{ env.WORKFLOW_ID }}

  build-with-nimble:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        flag:
          - ''
          - '-d:MINI'
        os:
          - ubuntu-16.04
          - macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install Nim
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "/home/runner/.nimble/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-fast update
          sudo apt-fast install -yq libgtk-3-dev libwebkit2gtk-4.0-dev
        if: matrix.os == 'ubuntu-16.04' && matrix.flag == ''

      - name: Verify dependecies
        run: |
          nim --version
          
      - name: Build Arturo
        run: |
          nimble build -Y ${{ matrix.flag }}

  build-mini-with-shell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "/home/runner/.nimble/bin" >> $GITHUB_PATH
          
      - name: Verify dependecies
        run: |
          nim --version
          
      - name: Build Arturo
        run: |
          ./build.sh mini

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install Nim
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "/home/runner/.nimble/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt-fast update
          sudo apt-fast install -yq libgtk-3-dev libwebkit2gtk-4.0-dev
        if: matrix.os == 'ubuntu-16.04'
          
      - name: Verify dependecies
        run: |
          nim --version
          
      - name: Build Arturo
        run: |
          ./build.sh install

      - name: Run unit tests
        run: |
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tests/runAll.art
