name: Linux
on: [push, pull_request]

jobs:
  cancel:
    name: "Cleanup"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: 1447568
          access_token: ${{ github.token }}
  build-mini:
    name: "Build (mini)"
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux64
      OPAMYES: 1
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          export PATH=/home/runner/.nimble/bin:$PATH
          echo "export PATH=/home/runner/.nimble/bin:$PATH" >> "$HOME/.bash_profile"
          
      - name: Verify dependecies
        shell: bash -l {0}
        run: |
          nim --version
          
      - name: Build Arturo
        shell: bash -l {0}
        run: |
          nimble build -Y "-d:MINI"

  build-full:
    name: "Build (full)"
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux64
      OPAMYES: 1
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          export PATH=/home/runner/.nimble/bin:$PATH
          echo "export PATH=/home/runner/.nimble/bin:$PATH" >> "$HOME/.bash_profile"
          
      - name: Verify dependecies
        shell: bash -l {0}
        run: |
          nim --version
          
      - name: Build Arturo
        shell: bash -l {0}
        run: |
          nimble build -Y
