name: macOS
on: [push, pull_request]

jobs:
  cancel:
    name: "Cleanup"
    runs-on: ubuntu-latest
    steps:
      - name: "Get workflow id"
        run: |
          WORKFLOW_ID=$(curl "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/macos.yml | jq '.id')
          echo "Workflow id: ${WORKFLOW_ID}"
          echo "::set-env name=WORKFLOW_ID::${WORKFLOW_ID}"

      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          access_token: ${{ github.token }}
          workflow_id: ${{ env.WORKFLOW_ID }}

  nimble-mini:
    name: "Nimble (mini)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "/Users/runner/.nimble/bin" >> $GITHUB_PATH
          
      - name: Verify dependecies
        shell: bash -l {0}
        run: |
          nim --version
          
      - name: Build Arturo
        shell: bash -l {0}
        run: |
          nimble build -Y "-d:MINI"

  nimble-full:
    name: "Nimble (full)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "/Users/runner/.nimble/bin" >> $GITHUB_PATH
          
      - name: Verify dependecies
        shell: bash -l {0}
        run: |
          nim --version
          
      - name: Build Arturo
        shell: bash -l {0}
        run: |
          nimble build -Y

  build-mini:
    name: "Build.sh (mini)"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "/Users/runner/.nimble/bin" >> $GITHUB_PATH
          
      - name: Verify dependecies
        shell: bash -l {0}
        run: |
          nim --version
          
      - name: Build Arturo
        shell: bash -l {0}
        run: |
          ./build.sh mini

  unit-tests:
    name: "Unit tests"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "/Users/runner/.nimble/bin" >> $GITHUB_PATH
          
      - name: Verify dependecies
        shell: bash -l {0}
        run: |
          nim --version
          
      - name: Build Arturo
        shell: bash -l {0}
        run: |
          ./build.sh install

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pwd
          ls -la
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          arturo tests/runAll.art   
